# Site settings
title: Josh Mitchell - Web Developer - Visual Media Producer
description: "A blog to keep track of the projects that I am working on"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://jmitchvii.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Josh Mitchell
user_title: JMitchVII
email: JoshMitchell.vii@gmail.com
twitter_username: loremipsum
github_username:  JMitchVII
gplus_username:  JoshMitchell.vii@gmail.com
disqus_username: loremipsum
profile_picture: https://scontent.fsyd4-1.fna.fbcdn.net/v/t1.0-9/17425928_10202661436134016_6530836516798783759_n.jpg?oh=6f1ab46b17f45005c40b070b9bfca915&oe=59DD7E72

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
